### ISSUE TITLE
ycashd dumpd when i setgenerate true

### ISSUE THREAD

**Issue by squirrel1311** [ycashfoundation/yecwallet#11]
ycashd dumpd when i setgenerate true

<img src=https://touimg.com/u/20190719/1117552.png >

**Comment by hloo** [comment]
We recommend that you do NOT set generate to true. CPU mining is not cost effective, and you will never find a block.

Furthermore, the memory requirements of Equihash(192,7) are much higher than Equihash(200,9). You likely ran out of memory.
