### ISSUE TITLE
YecWallet for windows 2.0.5.2 doesnt start ycashd

### ISSUE THREAD

**Issue by bloxster** [ycashfoundation/yecwallet#12]
After installing YecWallet for Windows ver. 2.0.5.2 I receive an error as per the attached image, saying that couldnt start the embedded ycashd. Tried reinstalling and restarting several times with no result.

![photo_2019-07-20_10-17-18](https://user-images.githubusercontent.com/40316187/61576911-62e3c000-aae0-11e9-941c-3d3ad0bda144.jpg)

**Comment by argentum3** [comment]
@bloxster If you haven't found a solution for this, I'd suggest looking in your /Ycash/debug.log file and also the system crash reports (likely for the ycashd process that crashed) which should be at C:\ProgramData\Microsoft\Windows\WER\ReportArchive.  

Without knowing the error it's hard to troubleshoot.
That said, if the system crash report mentions Virtual Memory (VM), you may want to look into increasing the virtual memory. When I built a pc from parts and ran zecWallet, I had to increase the VM.
