### ISSUE TITLE
yecwallet stuck syncing

### ISSUE THREAD

**Issue by yeqbfgxjiq** [ycashfoundation/yecwallet#13]
yecwallet seems to be stuck syncing around 60%. It was loading just fine (same speed as zecwallet) up until around 60%. Since then it's slowed to a crawl. It make about 0.1% progress per hour. Is this to be expected and/or is there a quick fix?

**Comment by yeqbfgxjiq** [comment]
Ummm now there's a yellow triangle with an exclamation mark in the bottom right corner. Should I be concerned... I feel concerned 

![ummm](https://i.imgur.com/mFXkIQH.png)

**Comment by yeqbfgxjiq** [comment]
NVM it (the yellow triangle) went away. Still concerned tho... Why's it taking so long? zec-wallet synced in a few hours? This is taking days...

**Comment by Kuhar8198** [comment]
![yec](https://user-images.githubusercontent.com/53166555/61610464-ed076200-ac61-11e9-9e3d-00b9c067a419.jpg)
Same problem. 3 days and 62%... what's wrong with your wallet?!?!

**Comment by hloo** [comment]
@burrrata and @Kuhar8198, which operating system?

**Comment by Kuhar8198** [comment]
win 10. I have turned off the wallet, open ycashd.exe  and I was waiting 5 days until synchronized. And node always lost connections from 8 to 7 and then 5-6 to 1. In this stage need to close it and open again to have 8 connections... It was soooo difficult.

**Comment by hloo** [comment]
This is related to #14. See the workaround described there. While syncing blocks before the fork, use "connect" instead of "addnode" to make sure you are only connecting to Ycash nodes (not Zcash nodes).

**Comment by hloo** [comment]
This problem has now been fixed by the just-released YecWallet v.2.0.5.4.

**Comment by yeqbfgxjiq** [comment]
Is it fixed for Ubuntu 18.04 LTS as well?

**Comment by hloo** [comment]
Yes. It's now fixed for all platforms. Thank you for taking the time to file an issue.
