### ISSUE TITLE
yec wallet wont download full blockchain restarts

### ISSUE THREAD

**Issue by drinkability** [ycashfoundation/yecwallet#15]
get 2 about 50 percent shut off my computer I have 80 mg service it took 3 days 2 download half of the ledger and then every time other time I shut off my computer I have 2 start from scratch

**Comment by drinkability** [comment]
im on 5.0.3 now

**Comment by drinkability** [comment]
got my mining addresses and i set them high i know theres going 2 be be bugs

**Comment by drinkability** [comment]
ive been mining zec from the beginning 1st day

**Comment by drinkability** [comment]
theres a promplem with your wallet

**Comment by drinkability** [comment]
if im a node

**Comment by drinkability** [comment]
if it takes 3 days 2 download the ledger at my speed

**Comment by drinkability** [comment]
bullshit

**Comment by drinkability** [comment]
the old blockchain 2 the new fix your shit

**Comment by drinkability** [comment]
started new 5.23 percent

**Comment by drinkability** [comment]
2 hrs ago ill keep you updated

**Comment by drinkability** [comment]
my speed minutes

**Comment by hloo** [comment]
Please refrain from using profanity.

What operating system are you using?

**Comment by drinkability** [comment]
10

**Comment by drinkability** [comment]
home

**Comment by drinkability** [comment]
im well perversed in mining

**Comment by hloo** [comment]
The problem seems to affect users of Windows 10.

**Comment by drinkability** [comment]
i have asics and amd nvidia

**Comment by drinkability** [comment]
been doing it for yrs

**Comment by drinkability** [comment]
well why you help them out and suggest it i could go back to linux

**Comment by drinkability** [comment]
your not connected

**Comment by drinkability** [comment]
doesnt that seem odd

**Comment by drinkability** [comment]
i hate windows 10 i still have all my keys and you can go back and forth with some of them

**Comment by hloo** [comment]
Actually, a user that filed a similar issue is having a similar problem on Linux.

There are hundreds of nodes that synced just fine, but certainly some users are having issues similar to what you are experiencing. We will investigate. I apologize for the inconvenience.

**Comment by drinkability** [comment]
im patient i have pletty of time well see how the upgrade goes but its slow

**Comment by drinkability** [comment]
i have great service here in phoenix

**Comment by hloo** [comment]
When you said you were on "5.0.3", was that a typo?

**Comment by drinkability** [comment]
2.0.5.3

**Comment by drinkability** [comment]
yes

**Comment by drinkability** [comment]
drinking a little dealing with the old lady she hates me doing the crypto

**Comment by drinkability** [comment]
ill see if that works but it shoudnt take days

**Comment by hloo** [comment]
The next time it happens, examine your debug.log file and let us know what errors you see.

**Comment by drinkability** [comment]
syncing shouldnt take days i got up 2 45 percent and it tells me to restart d ok ill let you know and ill do the same on 2 of of my other computers

**Comment by drinkability** [comment]
i have like 10 running

**Comment by drinkability** [comment]
different configurations

**Comment by drinkability** [comment]
ill try my laptop no mining

**Comment by drinkability** [comment]
something wrong when i cant get a sync

**Comment by drinkability** [comment]
ill let it run let you know 6.44 percent 2 hrs

**Comment by drinkability** [comment]
ill keep my shit open10 pm az time

**Comment by drinkability** [comment]
i have 8 nodes cuts in and out and stops locks up

**Comment by hloo** [comment]
Again, I need to remind you to refrain from using profanity. Any further profanity, and I will close this thread.

Please look at your debug.log and let us know what errors you see.

**Comment by drinkability** [comment]
maybe its my end ill try my other computers this one 10 home id rather work on my pro versions

**Comment by drinkability** [comment]
or linux

**Comment by hloo** [comment]
See the workaround in #14.

**Comment by hloo** [comment]
This problem has now been fixed by the just-released YecWallet v.2.0.5.4.

**Comment by drinkability** [comment]
thanks hloo soon as I downloaded the new revision it went from slow crawl 2 have the full blockchain after 570000 in 2 hrs

**Comment by drinkability** [comment]
from 60 percent

**Comment by drinkability** [comment]
I believe in your project I hate buying asics after about a yr there useless feeding forien companys with the big farms especially china they sell 1 they keep 2 bitmain innsilicon then they make it any witch way then they come out with something better visious cycle
