### ISSUE TITLE
try 2 import all my keys at once only the first one shows up

### ISSUE THREAD

**Issue by drinkability** [ycashfoundation/yecwallet#16]
tried multiple times even doing one by one rescanning even redownloading the chain restarting from stratch some of them show up during the download but by the end no balances but the first address                   I inputted 1 by one into quarda i have 11 addresses but i imported 80 off jaxx liberty is that a problem

**Comment by drinkability** [comment]
version 2.0.55

**Comment by drinkability** [comment]
sorry 2 bother you again

**Comment by drinkability** [comment]
normal text 80 lines

**Comment by drinkability** [comment]
y cash says i have 116 addresses but only about 20 are accessable with the arrow my shielded are fine from what im mining

**Comment by hloo** [comment]
I will investigate the behavior that you are describing.

**Comment by drinkability** [comment]
after I get kicked off like a week I cant do anything see where my balances are

**Comment by drinkability** [comment]
with your 5.5 whatever

**Comment by drinkability** [comment]
i have keys

**Comment by drinkability** [comment]
they show up just fine in quarda everywhere else

**Comment by drinkability** [comment]
for my zec keys

**Comment by drinkability** [comment]
even cold storage keys show up on the chain not shielded

**Comment by drinkability** [comment]
that should show up right

**Comment by hloo** [comment]
Let me try to better understand the behavior that you are observing.

Let's say there are two private keys, A and B, exported from Jaxx Liberty.

Are you saying that if you import A and B (each on its own line of text), that only the address associated with A shows up with a balance in YecWallet?

If yes, have you confirmed on a block explorer that the address associated with B did indeed have a balance associated with it at the time of the fork?

You can use this tool, which converts between Ycash and Zcash addresses, to help in your inquiry:

https://addressconverter.zecwallet.co/
