### ISSUE TITLE
change description / tagline

### ISSUE THREAD

**Issue by sonyamann** [ycashfoundation/yecwallet#5]
I don't think I can do this in a pull request, or I'd just do that. You should edit this section:

<img width="1002" alt="Screen Shot 2019-06-05 at 11 29 25 PM" src="https://user-images.githubusercontent.com/17103438/59011551-f2ac0400-87e9-11e9-88b1-ae573af8e8ff.png">

It should reference Ycash, not Zcash :)

**Comment by hloo** [comment]
Thank you so much @sonyamann. I've edited the section.
